### ISSUE TITLE
Missing library .dll files for windows

### ISSUE THREAD

**Issue by FishmanL** [opendifferentialprivacy/smartnoise-core-python#27]
title -- dylib and so files are in the wheel, not dlls

**Comment by Shoeboxam** [comment]
This is because the rust library uses `gmp` and `mpfr` for high-precision floating point numbers, to help protect against floating-point attacks. These libraries are difficult to compile on the MSVC toolchain. We have statically compiled versions of these libraries via mingw, but building the .dll with vendored gmp/mpfr has not been completed yet.

In the meantime, I suggest WSL or a VM. If you are just developing a software product, you can compile the core library without the use-mpfr feature flag by setting the environment variable here:

**Comment by FishmanL** [comment]
Sounds good--would it be possible to note that on the readme?

**Comment by Shoeboxam** [comment]
There is a reference on the readme to the troubleshooting.md, with more information.

**Comment by raprasad** [comment]
@FishmanL There's a new release with .dll files. https://pypi.org/project/opendp-smartnoise-core/
(Note: the project has been renamed to from whitenoise to smartnoise)
